### ISSUE TITLE
KeyError:'ProfilePage'

### ISSUE THREAD

**Issue by onurbyrl** [SulimanHacker1/ig.osi#1]
I'm getting that error:

[+] getting profile ...Traceback (most recent call last):
  File "main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/home/kali/Downloads/ig.osi/api.py", line 59, in __init__
    self.get_profile()
  File "/home/kali/Downloads/ig.osi/api.py", line 67, in get_profile
    self.p_data = self.data['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'

Can you help me ?

**Comment by Vykolachips** [comment]
same

**Comment by MdRahul34** [comment]
Same

**Comment by chetan267518** [comment]
Same problem bro

**Comment by praga007deesh** [comment]
Same for me also
