### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by CollenMenezes** [SulimanHacker1/ig.osi#2]
I got this error...
`Traceback (most recent call last):
  File "main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/home/runner/igosi/api.py", line 59, in __init__
    self.get_profile()
  File "/home/runner/igosi/api.py", line 66, in get_profile
    self.data = json.loads(more_data[3].get_text()[21:].strip(';'))
IndexError: list index out of range`

**Comment by LUCIAWEN** [comment]
Listen what they do now is come telling you how helpful this or that man helped them recover their accounts or hack anything, i fell for those lies 5 times before i stumbled into the only legit man online Mr Bohdan who we worked through bohdanbohdan93 @ mail . ru doing this to save any victim out there please be careful anyone different from him is another possible fake my friend

**Comment by AM-660** [comment]
same problem..!
