### ISSUE TITLE
getting profile ...Traceback (most recent call last)

### ISSUE THREAD

**Issue by swasthikmoolya** [SulimanHacker1/ig.osi#4]
File "/home/kali/ig.osi/main.py", line 16, in <module>
    ig = main(user=args["username"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/ig.osi/api.py", line 59, in __init__
    self.get_profile()
  File "/home/kali/ig.osi/api.py", line 64, in get_profile
    soup = BeautifulSoup(profile.text, 'html.parser')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 215, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 160, in handle_decl
    self.soup.endData(Doctype)
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 1054, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 1292, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 1313, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 1610, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 1615, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by Roohankhan0909** [comment]
Same problems

**Comment by ABD123758** [comment]
Same problem
